[package]
name = "red-planet-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
red-planet-core = { path = "../red-planet-core" }
stderrlog = "0.6.0"
