[package]
name = "space-time"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast-rs = "1.2.0"
generational-arena = "0.2.9"
nohash = "0.2.0"
